import { Geist, Geist_Mono } from "next/font/google";
import clsx from "clsx";
import "./globals.css";
import Script from "next/script";

import AuthProvider from "@/app/components/auth/AuthProvider";
import AuthRedirect from "@/app/components/auth/AuthRedirect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet"></link>
        <Script
          src="https://unpkg.com/threebox-plugin/dist/threebox.min.js"
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={clsx(`${geistSans.variable} ${geistMono.variable} antialiased`, "bg-white dark:bg-slate-900 text-black dark:text-white")}
      >
        <AuthProvider>
          <AuthRedirect>
            {children}
          </AuthRedirect>
        </AuthProvider>
      </body>
    </html>
  );
}
