services:
  localstack:
    image: localstack/localstack:latest
    container_name: stackbox-localstack
    ports:
      - "4566:4566"  # LocalStack gateway
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack-init:/etc/localstack/init/ready.d"  # Init scripts
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack-data:/var/lib/localstack"
    networks:
      - stackbox-network

volumes:
  localstack-data:

networks:
  stackbox-network:
    driver: bridge
