# Have to use Debian or Ubuntu due to VTK
FROM python:3.14.3-slim-trixie
WORKDIR /app
EXPOSE 8000

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN echo "/app/src" > /usr/local/lib/python3.14/site-packages/project-paths.pth